name: Publish to NPM

on:
  push:
    branches: [release]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (patch, minor, major, or specific version like 1.2.3)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup Python (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Visual Studio Build Tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Rebuild native dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: npm rebuild better-sqlite3 --build-from-source
        
      - name: Run tests
        run: npm run test:ci
        
      - name: Build project
        run: npm run build

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Build project
        run: npm run build

      - name: Bump version (release branch or manual trigger)
        if: github.ref == 'refs/heads/release' || github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual trigger - use specified version
            if [[ "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              npm version ${{ github.event.inputs.version }} --no-git-tag-version
            else
              npm version ${{ github.event.inputs.version }} --no-git-tag-version
            fi
          else
            # Release branch push - auto patch bump
            npm version patch --no-git-tag-version
          fi
          
          git add package.json package-lock.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")" || true
          git push || true

      - name: Create Git tag (release branch or manual trigger)
        if: github.ref == 'refs/heads/release' || github.event_name == 'workflow_dispatch'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag -a "v$VERSION" -m "Release v$VERSION" || true
          git push origin "v$VERSION" || true

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          release_name: Release v${{ steps.version.outputs.new_version }}
          body: |
            ## Changes
            - Version bump to ${{ steps.version.outputs.new_version }}
            
            Install with: `npm install mini-todo-list-mcp`
            
            ## MCP Server Usage
            Add to your Claude Desktop config:
            ```json
            {
              "mcpServers": {
                "mini-todo": {
                  "command": "node",
                  "args": ["/path/to/node_modules/mini-todo-list-mcp/dist/index.js"]
                }
              }
            }
            ```
          draft: false
          prerelease: false